-- Supabase (PostgreSQL) uchun xuddi shu sxema.
-- Supabase > SQL Editor ga nusxalab ishga tushirsangiz bo'ladi.
-- Ustun nomlari SQLite bilan bir xil, shuning uchun ma'lumotni
-- CSV orqali to'g'ridan-to'g'ri ko'chirish mumkin.

CREATE TABLE IF NOT EXISTS shops (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              TEXT        NOT NULL,
    owner_telegram_id BIGINT,
    channel_id        TEXT,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS products (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id            BIGINT      NOT NULL REFERENCES shops(id),
    brand              TEXT        NOT NULL,
    source             TEXT,
    packs_total        INTEGER     NOT NULL,
    packs_sold         INTEGER     NOT NULL DEFAULT 0,
    cost_price         BIGINT,
    sale_price         BIGINT      NOT NULL,
    currency           TEXT        NOT NULL DEFAULT 'UZS',
    extra_info         TEXT        NOT NULL DEFAULT '',
    raw_caption        TEXT        NOT NULL DEFAULT '',
    description        TEXT        NOT NULL DEFAULT '',
    barcode            TEXT UNIQUE,
    status             TEXT        NOT NULL DEFAULT 'pending',
    preview_chat_id    BIGINT,
    preview_message_id BIGINT,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    published_at       TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_products_shop_status ON products(shop_id, status);

CREATE TABLE IF NOT EXISTS product_images (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id        BIGINT      NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    position          INTEGER     NOT NULL,
    original_file_id  TEXT        NOT NULL,
    processed_file_id TEXT,
    local_path        TEXT,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_images_product ON product_images(product_id);

CREATE TABLE IF NOT EXISTS channel_messages (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT      NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    chat_id    TEXT        NOT NULL,
    message_id BIGINT      NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_channel_messages_product ON channel_messages(product_id);
